#!/usr/bin/env python3
"""Rebuild deterministic Markdown and JSONL views from data/news.json."""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

from news_common import (
    CATEGORIES,
    CATEGORY_LABELS,
    atomic_write_text,
    find_repo_root,
    load_items,
    markdown_escape,
)
from validate_news import validate_database


GENERATED_MARKER = "<!-- generated by rebuild_index.py; do not edit -->"
EMPTY_MESSAGE = "No published news yet. / 暂无已发布新闻。"


def sort_items(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(items, key=lambda item: (item["published_at"], item["id"]), reverse=True)


def markdown_links(urls: list[str], label: str) -> str:
    if not urls:
        return ""
    links = " · ".join(f"[{label} {index}]({url})" for index, url in enumerate(urls, start=1))
    return links


def render_entry(item: dict[str, Any]) -> str:
    source = item["source"]
    category_text = ", ".join(CATEGORY_LABELS[category] for category in item["categories"])
    tag_text = ", ".join(f"`{tag}`" for tag in item["tags"]) or "—"
    lines = [
        f'<a id="{item["id"]}"></a>',
        f'## [{markdown_escape(item["title_zh"])}]({source["url"]})',
        "",
        f'**English:** [{markdown_escape(item["title_en"])}]({source["url"]})',
        "",
        f'- **发布 / Published:** `{item["published_at"]}`',
        f'- **来源 / Source:** [{markdown_escape(source["name"])}]({source["url"]}) · `{source["type"]}`',
        f'- **分类 / Categories:** {category_text}',
        f'- **标签 / Tags:** {tag_text}',
        f'- **可信度 / Confidence:** `{item["confidence"]}` · **评分 / Score:** `{item["score"]}/100`',
        "",
        "### 摘要 / Summary",
        "",
        item["summary_zh"],
        "",
        item["summary_en"],
        "",
        "### 技术点 / Technical points",
        "",
    ]
    for zh_point, en_point in zip(item["tech_points_zh"], item["tech_points_en"]):
        lines.extend([f"- {zh_point}", f"  - {en_point}"])
    lines.extend(
        [
            "",
            "### 为什么重要 / Why it matters",
            "",
            item["why_it_matters_zh"],
            "",
            item["why_it_matters_en"],
        ]
    )
    evidence = markdown_links(item["evidence_urls"], "Evidence")
    discussion = markdown_links(item["discussion_urls"], "Discussion")
    if evidence or discussion:
        lines.extend(["", "### 链接 / Links", ""])
        if evidence:
            lines.append(evidence)
        if discussion:
            lines.append(discussion)
    return "\n".join(lines)


def render_page(title: str, items: list[dict[str, Any]]) -> str:
    lines = [GENERATED_MARKER, "", f"# {title}", ""]
    if not items:
        lines.extend([EMPTY_MESSAGE, ""])
    else:
        lines.append("\n\n---\n\n".join(render_entry(item) for item in items))
        lines.append("")
    return "\n".join(lines)


def build_outputs(root: Path, items: list[dict[str, Any]]) -> dict[Path, str]:
    sorted_news = sort_items(items)
    outputs: dict[Path, str] = {}

    jsonl = "".join(json.dumps(item, ensure_ascii=False, sort_keys=True) + "\n" for item in sorted_news)
    outputs[root / "data" / "news.jsonl"] = jsonl
    outputs[root / "LATEST.md"] = render_page("Latest frontier AI news / 最新前沿 AI 新闻", sorted_news[:20])

    by_date: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in sorted_news:
        by_date[item["published_at"][:10]].append(item)

    index_lines = [GENERATED_MARKER, "", "# News archive / 新闻归档", ""]
    if not by_date:
        index_lines.extend([EMPTY_MESSAGE, ""])
    else:
        for date in sorted(by_date, reverse=True):
            year, month, _ = date.split("-")
            index_lines.append(f"- [{date}]({year}/{month}/{date}.md) — {len(by_date[date])} item(s)")
        index_lines.append("")
    outputs[root / "news" / "index.md"] = "\n".join(index_lines)

    for date, date_items in by_date.items():
        year, month, _ = date.split("-")
        outputs[root / "news" / year / month / f"{date}.md"] = render_page(
            f"{date} frontier AI news / 前沿 AI 新闻", date_items
        )

    for category in CATEGORIES:
        category_items = [item for item in sorted_news if category in item["categories"]]
        outputs[root / "topics" / f"{category}.md"] = render_page(CATEGORY_LABELS[category], category_items)

    return outputs


def existing_generated_files(root: Path) -> set[Path]:
    files = {
        root / "data" / "news.jsonl",
        root / "LATEST.md",
        root / "news" / "index.md",
        *(root / "topics" / f"{category}.md" for category in CATEGORIES),
    }
    news_root = root / "news"
    if news_root.exists():
        for path in news_root.glob("*/*/*.md"):
            try:
                first_line = path.read_text(encoding="utf-8").splitlines()[0]
            except (OSError, IndexError):
                continue
            if first_line == GENERATED_MARKER:
                files.add(path)
    return {path for path in files if path.exists()}


def check_outputs(root: Path, outputs: dict[Path, str]) -> list[str]:
    problems: list[str] = []
    for path, expected in outputs.items():
        if not path.exists():
            problems.append(f"missing generated file: {path.relative_to(root)}")
        elif path.read_text(encoding="utf-8") != expected:
            problems.append(f"stale generated file: {path.relative_to(root)}")
    for stale in existing_generated_files(root) - outputs.keys():
        problems.append(f"obsolete generated file: {stale.relative_to(root)}")
    return sorted(problems)


def write_outputs(root: Path, outputs: dict[Path, str]) -> tuple[list[Path], list[Path]]:
    changed = [path for path, content in outputs.items() if atomic_write_text(path, content)]
    removed: list[Path] = []
    for stale in existing_generated_files(root) - outputs.keys():
        stale.unlink()
        removed.append(stale)
    return changed, removed


def build_parser() -> argparse.ArgumentParser:
    root = find_repo_root()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=root / "data" / "news.json")
    parser.add_argument("--check", action="store_true", help="Check generated files without writing")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    root = find_repo_root(args.input.resolve())
    errors, warnings, count = validate_database(args.input.resolve())
    if errors:
        for message in errors:
            print(f"ERROR: {message}", file=sys.stderr)
        print("Refusing to render an invalid database", file=sys.stderr)
        return 1
    for message in warnings:
        print(f"WARNING: {message}", file=sys.stderr)
    try:
        items = load_items(args.input.resolve())
        outputs = build_outputs(root, items)
    except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError) as exc:
        print(f"ERROR: could not build outputs ({exc})", file=sys.stderr)
        return 1

    if args.check:
        problems = check_outputs(root, outputs)
        for problem in problems:
            print(f"ERROR: {problem}", file=sys.stderr)
        if problems:
            return 1
        print(f"Generated outputs are current for {count} news item(s)")
        return 0

    changed, removed = write_outputs(root, outputs)
    print(f"Rebuilt {len(outputs)} output(s) for {count} news item(s): {len(changed)} changed, {len(removed)} removed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
